[package]
name = "kudusql"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "MIT/Apache-2.0"
description = "SQL-like shell for Apache Kudu (Incubating)"
keywords = ["kudu", "database"]

[dependencies]
kudu = { git = "https://github.com/danburkert/kudu-rs" }
