[package]
name = "kudusql"
version = "0.1.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "MIT/Apache-2.0"
description = "SQL-like shell for Apache Kudu (Incubating)"
keywords = ["kudu", "database"]

[dependencies]
docopt = "0.6"
kudu = { git = "https://github.com/danburkert/kudu-rs" }
linenoise-rust = "0.1"
nom = "1.2"
rustc-serialize = "0.3"
